### ISSUE TITLE
Error: Redis connection to redis:6379 failed

### ISSUE THREAD

**Issue by allthesignals** [codefornl/carto-sql-api-docker#1]
I was able to set this up locally on my machine, but I thought it'd make more sense to look for this docker implementation.

I'm seeing the following error on startup: 
```
[2017-05-31 19:17:57.024] [ERROR] [default] - Uncaught exception: Error: Redis connection to redis:6336 failed - getaddrinfo ENOTFOUND
    at RedisClient.on_error (/cartodb-sql-api/node_modules/redis-mpool/node_modules/redis/index.js:196:24)
    at Socket.<anonymous> (/cartodb-sql-api/node_modules/redis-mpool/node_modules/redis/index.js:106:14)
    at Socket.EventEmitter.emit (events.js:95:17)
    at net.js:830:16
    at process._tickCallback (node.js:415:13)
```

This may be related to the issue, but which username subdomain do I use? Possibly, I have to have one defined in the redis store that it can't access.

**Comment by allthesignals** [comment]
Looks like a fairly lengthy build process for redis: https://www.digitalocean.com/community/tutorials/how-to-install-and-configure-redis-on-ubuntu-16-04. 

It's not super important to me that the "cartodb user" concept is working if we're just looking to point SQL API to a database. Maybe there's a way to get around this?
